### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by Redsandro** [kiddkai/atom-node-debugger#163] opened 2016-04-11 22:07 UTC
The node debugger for Eclipse has next to `breakpoints` and `locals` also a tab called `expressions` where you can type in a small expression per line that evaluates to its value using locals.

E.g. `foo == 2 && bar == baz` would evaluate to `true` or `false` so you can resume debugging with a breakpoint in a loop and quickly iterate until a certain condition you're looking for is true.

It can evaluate to anything you can put in a variable. You can also just type a shortcut to an object, e.g. `args.req.headers`.

**Comment by codecontemplator** [comment] 2016-04-30 23:31
Thanks for your feedback. This would indeed be useful. I close it as a duplicate of #124 though since I think this would be solved by the watch window beeing discussed there.

**Closed by codecontemplator** 2016-04-30 23:31 UTC
