### ISSUE TITLE
Can you allow us to debug a currently running instance that is already debugging?

### ISSUE THREAD

**Issue by intervalia** [kiddkai/atom-node-debugger#125] opened 2016-02-10 19:08 UTC
At work I have a complicated startup process for my node apps. I can't just have your debugger start my app. I need to be able to have your debugger attach itself to an already running instance of a node app.

Can this be done?
Mike

**Comment by akoskm** [comment] 2016-02-13 10:29
duplicate of https://github.com/kiddkai/atom-node-debugger/issues/23

**Comment by codecontemplator** [comment] 2016-02-18 20:32
Duplicate of #23

**Closed by codecontemplator** 2016-02-18 20:32 UTC
