### ISSUE TITLE
getting slower after a while

### ISSUE THREAD

**Issue by depend** [kiddkai/atom-node-debugger#131] opened 2016-02-18 21:39 UTC
Everything starts out well. But after doing F5 and Shift-F5 10-20 times, it takes 10 or more seconds to start debugging. During that 10+ seconds Atom process takes 100% of one core and UI is unresponsive. node process seems fine. The only way to recover is to restart atom. My environment is Windows 10 64bit, Atom 1.5.3, node 64bit 4.2.2, node-debugger 1.3.2.

**Comment by codecontemplator** [comment] 2016-02-20 16:13
Hmm. I know there is a problem with leaked event listeners and that might be the cause of this problem.

**Comment by codecontemplator** [comment] 2016-05-10 19:57
Merged #171 but I leave this open since there are still leak event listeners. Not sure which ones though but the console output displays evidence.

**Comment by codecontemplator** [comment] 2016-10-14 21:11
Fixed

**Closed by codecontemplator** 2016-10-14 21:11 UTC
Labels: bug
